[tools]
rojo = {github = "rojo-rbx/rojo", version = "7.6.1"}
wally = {github = "UpliftGames/wally", version = "0.3.2"}
selene = {github = "kampfkarren/selene", version = "0.30.1"}
luau-lsp = {github = "JohnnyMorganz/luau-lsp", version = "1.65.0"}
