[package]
name = "butchhartman/rblx-tool-test"
version = "0.1.0"
registry = "https://github.com/upliftgames/wally-index"
realm = "shared"
# Prevents publshing of our game lol
private = true

[place]
server-packages = "game.ReplicatedStorage.Packages"

[dev-dependencies]
TestEZ = "roblox/testez@0.4.1"

